# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
name: TxNotify
options:
  bundleIdPrefix: com.vivianphung
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
packages:
  Starscream:
    url: https://github.com/daltoniam/Starscream
    from: 3.0.0
  Web3:
    url: https://github.com/WalletConnect/Web3.swift
    exactVersion: 1.0.2
  WalletConnect:
    url: https://github.com/WalletConnect/WalletConnectSwiftV2
    from: 1.2.0
targets:
  TxNotify:
    name: TxNotify
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    scheme: {}
    configFiles:
      Debug: configs/TxNotify-Debug.xcconfig
      Release: configs/TxNotify-Release.xcconfig
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.vivianphung.TxNotify
        DEVELOPMENT_TEAM: FG655QY4XD
        SUPPORTS_MACCATALYST: NO
      debug:
      release:
    sources:
      - path: "TxNotify"
        name: "TxNotify"
      - path: "README.md"
        buildPhase: none
      - path: "project.yml"
        buildPhase: none
      - path: ".swiftlint.yml"
        buildPhase: none
      - path: "Info.plist"
        buildPhase: none
      - path: ".gitignore"
        buildPhase: none
    dependencies:
      - package: Starscream
      - package: Web3
      - package: WalletConnect
        product: WalletConnectChat
      - package: WalletConnect
        product: Web3Wallet
      - package: WalletConnect
        product: WalletConnectPush
      - package: WalletConnect
        product: WalletConnectEcho
      - package: WalletConnect
        product: WalletConnectPairing
      - package: WalletConnect
        product: WalletConnectNetworking
      - package: WalletConnect
        product: WalletConnectRouter
      - package: WalletConnect
        product: WalletConnectVerify
    info:
      path: Info.plist
      properties:
        PROJECT_ID: $(PROJECT_ID)
        UILaunchScreen:
          UIColorName: LaunchBackground
          UIImageName: AppIcon
        CFBundleShortVersionString: "1"
        CFBundleVersion: "1.0"
        ITSAppUsesNonExemptEncryption: false
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIViewControllerBasedStatusBarAppearance: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    entitlements:
      path: TxNotify.entitlements
      properties:
        keychain-access-groups: []
    postCompileScripts:
      - script: /opt/homebrew/bin/swiftlint --fix
        name: Run SwiftLint
        basedOnDependencyAnalysis: false
